//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRPS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public string Party_Ref { get; set; }
        public string Address_Code { get; set; }
        public string Contact_Name { get; set; }
        public string Contact_Title { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string Address_3 { get; set; }
        public string Address_4 { get; set; }
        public string Address_5 { get; set; }
        public string Post_Code { get; set; }
        public string Telephone_No { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public System.DateTime Version_Date { get; set; }
        public int Version_No { get; set; }
    
        public virtual Party Party { get; set; }
    }
}
