//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRPS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppLog
    {
        public int Log_Id { get; set; }
        public string Status { get; set; }
        public string Job_Desc { get; set; }
        public System.DateTime Log_Time { get; set; }
        public string Message { get; set; }
    }
}
