//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRPS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BRPSDbContext : DbContext
    {
        public BRPSDbContext()
            : base("name=BRPSDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<AppLog> AppLogs { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Market> Markets { get; set; }
        public virtual DbSet<Party> Parties { get; set; }
        public virtual DbSet<Salesperson> Salespersons { get; set; }
        public virtual DbSet<ScheduledJob> ScheduledJobs { get; set; }
        public virtual DbSet<ScheduledJobParam> ScheduledJobParams { get; set; }
        public virtual DbSet<ExchangeRate> ExchangeRates { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<ClientAccount> ClientAccounts { get; set; }
        public virtual DbSet<TradeCharge> TradeCharges { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Code_Mapping> Code_Mapping { get; set; }
        public virtual DbSet<Trans_Code_Desc> Trans_Code_Desc { get; set; }
        public virtual DbSet<Transaction_Type> Transaction_Type { get; set; }
        public virtual DbSet<Trade_NarrativeInfo> Trade_NarrativeInfo { get; set; }
        public virtual DbSet<Instrument_Price> Instrument_Price { get; set; }
        public virtual DbSet<Warrant> Warrants { get; set; }
        public virtual DbSet<Trade> Trades { get; set; }
        public virtual DbSet<Client_CashBalance> Client_CashBalance { get; set; }
        public virtual DbSet<Client_StockBalance> Client_StockBalance { get; set; }
        public virtual DbSet<TradeCharge_AmendedComm> TradeCharge_AmendedComm { get; set; }
        public virtual DbSet<Trade_Status> Trade_Status { get; set; }
        public virtual DbSet<Trade_Cancelled> Trade_Cancelled { get; set; }
        public virtual DbSet<Instrument> Instruments { get; set; }
    }
}
