//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRPS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public string Client_Number { get; set; }
        public string Client_Title { get; set; }
        public string Short_Name { get; set; }
        public string Long_Name { get; set; }
        public string Marital_Status { get; set; }
        public Nullable<System.DateTime> Birth_Incorp_Date { get; set; }
        public string SG_PR { get; set; }
        public string Client_Account_Number { get; set; }
        public string Identification_Type { get; set; }
        public string Unique_ID { get; set; }
        public string Issuing_Country { get; set; }
        public string Ownership_Category_Code { get; set; }
        public string Principal_Business { get; set; }
        public string Residence_Code { get; set; }
        public string Occupation { get; set; }
        public string Employment_Status { get; set; }
        public string Employer_Name { get; set; }
        public string EU_Corporate_Sector { get; set; }
        public string Financial_nature { get; set; }
        public string LEI_Name { get; set; }
        public string LEI { get; set; }
        public string Parent_Company { get; set; }
        public string Location { get; set; }
        public string Paidup_Captital { get; set; }
        public string Annual_Income { get; set; }
        public string Net_Worth { get; set; }
        public string Accredited_Investor { get; set; }
        public string Risk_Tolerance { get; set; }
        public string High_Risk_Factors { get; set; }
        public string AC_Openning_Doc { get; set; }
        public string Standing_Authority { get; set; }
        public string Trading_Account_Type { get; set; }
        public string Client_Type { get; set; }
        public string Client_Status { get; set; }
        public int Version_No { get; set; }
        public System.DateTime Version_Date { get; set; }
        public string Status { get; set; }
        public string Country { get; set; }
    
        public virtual Party Party { get; set; }
        public virtual ClientAccount ClientAccount { get; set; }
    }
}
