//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRPS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientAccount()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public string Client_Account_Number { get; set; }
        public string Position_Account_Number { get; set; }
        public string Position_Account_Category { get; set; }
        public string Position_Account_Origin { get; set; }
        public string Account_Status { get; set; }
        public string Position_Account_Type { get; set; }
        public string Party_Custody_Type { get; set; }
        public string Remisier_Code { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Activated_Date { get; set; }
        public Nullable<System.DateTime> Closed_Date { get; set; }
        public Nullable<System.DateTime> Suspended_Date { get; set; }
        public Nullable<System.DateTime> Last_Amend_Date { get; set; }
        public Nullable<System.DateTime> Last_Transction_Date { get; set; }
        public string Suspension_Reasons { get; set; }
        public string Default_Settle_Curr { get; set; }
        public bool Contra_Eligible { get; set; }
        public bool Is_Truth_Account { get; set; }
        public bool Online_Eligible { get; set; }
        public Nullable<decimal> Buy_Limit { get; set; }
        public Nullable<decimal> Sell_Limit { get; set; }
        public Nullable<decimal> Margin_Credit_Limit { get; set; }
        public string GST_Status_Code { get; set; }
        public string Payment_Mode { get; set; }
        public string EPS_Link_Status { get; set; }
        public Nullable<System.DateTime> EPS_Commence_Date { get; set; }
        public Nullable<System.DateTime> EPS_Close_Date { get; set; }
        public string EPS_Bank_No { get; set; }
        public string EPS_Bank_Acct { get; set; }
        public string GIRO_Payment_Type { get; set; }
        public string GIRO_Bank_No { get; set; }
        public string GIRO_Bank_Acct { get; set; }
        public string SRS_Bank_No { get; set; }
        public string SRS_Bank_Acct { get; set; }
        public string CPF_Bank_No { get; set; }
        public string CPF_Bank_Acct { get; set; }
        public string Trade_Confirmation { get; set; }
        public string Parent_Account { get; set; }
        public string Securities_Account { get; set; }
        public string Suspense_Account { get; set; }
        public string Related_Account { get; set; }
        public string SCB_Invest_Mgmt_AC { get; set; }
        public string SCB_Truth_Account { get; set; }
        public string Relationship { get; set; }
        public string CDP_Acct_Linkage_Status { get; set; }
        public Nullable<System.DateTime> CDP_Acct_Linkage_Date { get; set; }
        public Nullable<System.DateTime> CDP_Acct_Linkage_Revoc_Date { get; set; }
        public string CDP_Acct_Linkage_Reject_Code { get; set; }
        public string Client_DA_Code { get; set; }
        public string Capacity { get; set; }
        public string Segregation { get; set; }
        public string EPS_Bank_Name { get; set; }
        public string SGX_Client_No { get; set; }
        public string KLSE_CDS_Account_Code { get; set; }
        public string SCB_IMA_NO_SG { get; set; }
        public string SCB_TRUST_AC_NO_SG { get; set; }
        public string Status_Narrative { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients { get; set; }
    }
}
