//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRPS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_StockBalance
    {
        public long RecID { get; set; }
        public string Client_Account_Number { get; set; }
        public string Ccy { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string Type { get; set; }
    }
}
