//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRPS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Code_Mapping
    {
        public string Category { get; set; }
        public string Class { get; set; }
        public string Type { get; set; }
        public string Value { get; set; }
        public string Mapped_Value { get; set; }
        public string Description { get; set; }
    }
}
