//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRPS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeRate
    {
        public string CCYPairID { get; set; }
        public string Instr_Ref { get; set; }
        public string Quote_Instr_Ref { get; set; }
        public decimal Mid_Price { get; set; }
        public decimal Bid_Price { get; set; }
        public decimal Ask_Price { get; set; }
        public System.DateTime Price_DateTime { get; set; }
    }
}
