//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRPS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public string Holiday_Id { get; set; }
        public System.DateTime Holiday_Date { get; set; }
        public int Weekend_Day { get; set; }
        public System.DateTime Version_Date { get; set; }
        public int Version_No { get; set; }
    }
}
