//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRPS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrument_Price
    {
        public long RecID { get; set; }
        public string Instr_Ref { get; set; }
        public Nullable<double> Close_Price { get; set; }
        public Nullable<System.DateTime> Price_date { get; set; }
        public Nullable<System.DateTime> Version_date { get; set; }
        public Nullable<int> Version_no { get; set; }
    }
}
