//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRPS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrument
    {
        public string Instr_Ref { get; set; }
        public string Instr_Group { get; set; }
        public string Long_Name { get; set; }
        public string Short_Name { get; set; }
        public string Main_Market { get; set; }
        public string Denom_Ccy { get; set; }
        public int Denom_Qty { get; set; }
        public string Settle_Instr { get; set; }
        public string Book { get; set; }
        public int Price_Decimal_Place { get; set; }
        public decimal Price_Divisor { get; set; }
        public decimal Price_Multiplier { get; set; }
        public string Price_Type { get; set; }
        public int Min_Tradeable_Qty { get; set; }
        public int Qty_Decimal_Place { get; set; }
        public string Active_Ind { get; set; }
        public Nullable<System.DateTime> Listing_Date { get; set; }
        public Nullable<System.DateTime> Delisting_Date { get; set; }
        public string Proprietary_Code { get; set; }
        public string Local_Code { get; set; }
        public string SG_CDP_Code { get; set; }
        public string ISIN_Code { get; set; }
        public string BMBG_Code { get; set; }
        public string RIC_Code { get; set; }
        public string SEDL_Code { get; set; }
        public string COMM_Code { get; set; }
        public string CFI_Code { get; set; }
        public string Security_Type { get; set; }
        public string Country { get; set; }
        public string Domicile_Country { get; set; }
        public string Margin_Category { get; set; }
        public Nullable<decimal> Margin_Ratio { get; set; }
        public Nullable<decimal> Margin_Limit { get; set; }
        public string Product_Type { get; set; }
        public string Security_Tax_Type { get; set; }
        public string Settlemet_Driver { get; set; }
        public System.DateTime Version_Date { get; set; }
        public int Version_No { get; set; }
        public string Symbol_Code { get; set; }
        public Nullable<decimal> Close_Price { get; set; }
        public string Group_Code { get; set; }
    
        public virtual Warrant Warrant { get; set; }
    }
}
