//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRPS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Market
    {
        public string Market_Code { get; set; }
        public string Country { get; set; }
        public string Location { get; set; }
        public string Holiday_Id { get; set; }
        public string Value_Date_Rule_B { get; set; }
        public string Value_Date_Rule_S { get; set; }
        public string Market_Name { get; set; }
    }
}
