//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRPS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salesperson
    {
        public string Salesperson_Ref { get; set; }
        public string Short_Name { get; set; }
        public string Long_Name { get; set; }
        public string Country { get; set; }
        public string Location { get; set; }
        public string Title { get; set; }
        public string Holiday_Calendar { get; set; }
        public string Reporting_Curr { get; set; }
        public string Segregation_Party { get; set; }
        public string Active { get; set; }
        public bool Template { get; set; }
        public string Bloomberg_Ref { get; set; }
        public string Dept_Code { get; set; }
        public string Sales_Group { get; set; }
        public string GL_User_ID { get; set; }
        public string Salesperson_Ref_1 { get; set; }
        public string Salesperson_Ref_2 { get; set; }
        public string Salesperson_Ref_3 { get; set; }
        public string MAS_Rep_No { get; set; }
        public string SGX_TR_Code { get; set; }
        public string Salesperson_Category { get; set; }
        public System.DateTime Joining_Date { get; set; }
        public Nullable<System.DateTime> Departure_Date { get; set; }
        public Nullable<System.DateTime> Obtaining_M6A_Date { get; set; }
        public string Own_Trading_AC_No_1 { get; set; }
        public string Own_Trading_AC_No_2 { get; set; }
        public string Own_Trading_AC_No_3 { get; set; }
        public string Cost_Centre { get; set; }
        public string Backup_Salesperson { get; set; }
        public string Info_Narrative { get; set; }
        public string Status_Narrative { get; set; }
        public string Internal_Narrative { get; set; }
        public int Version_No { get; set; }
        public System.DateTime Version_Date { get; set; }
    
        public virtual Party Party { get; set; }
    }
}
