//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRPS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledJob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduledJob()
        {
            this.ScheduledJobParams = new HashSet<ScheduledJobParam>();
        }
    
        public int Job_Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> Depend_Job_Id { get; set; }
        public string Occurence { get; set; }
        public int Interval { get; set; }
        public string From_Time { get; set; }
        public string End_Time { get; set; }
        public string Process { get; set; }
        public int Status { get; set; }
        public System.DateTime Business_Date { get; set; }
        public Nullable<System.DateTime> Last_Execution_Time { get; set; }
        public string Message { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduledJobParam> ScheduledJobParams { get; set; }
    }
}
