//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRPS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledJobParam
    {
        public int Param_Id { get; set; }
        public int Job_Id { get; set; }
        public int Param_Order { get; set; }
        public string Param_Name { get; set; }
        public string Param_Type { get; set; }
        public string Param_Value { get; set; }
    
        public virtual ScheduledJob ScheduledJob { get; set; }
    }
}
