//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRPS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeCharge_AmendedComm
    {
        public long RecID { get; set; }
        public string Client_Number { get; set; }
        public string Trade_Ref { get; set; }
        public long Trade_No { get; set; }
        public decimal Commission { get; set; }
        public System.DateTime Trade_Date { get; set; }
        public System.DateTime Created_Date { get; set; }
    }
}
