//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRPS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade_NarrativeInfo
    {
        public long RecID { get; set; }
        public long Trade_No { get; set; }
        public string Narrative_Code { get; set; }
        public string Narrative { get; set; }
        public Nullable<System.DateTime> Version_date { get; set; }
        public Nullable<int> Version_no { get; set; }
    }
}
