//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRPS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeCharge
    {
        public System.DateTime Business_Date { get; set; }
        public long Trade_No { get; set; }
        public string Curr { get; set; }
        public decimal Commission { get; set; }
        public decimal Commission_GST { get; set; }
        public decimal Clearing_Fee { get; set; }
        public decimal Clearing_Fee_GST { get; set; }
        public decimal Trading_Fee { get; set; }
        public decimal Trading_Fee_GST { get; set; }
        public decimal Settlement_Fee { get; set; }
        public decimal Stamp_Duty_Fee { get; set; }
        public decimal Transaction_Levy_Fee { get; set; }
        public decimal Commission_SGD { get; set; }
        public decimal Commission_GST_SGD { get; set; }
        public decimal Clearing_Fee_SGD { get; set; }
        public decimal Clearing_Fee_GST_SGD { get; set; }
        public decimal Trading_Fee_SGD { get; set; }
        public decimal Trading_Fee_GST_SGD { get; set; }
        public decimal Settlement_Fee_SGD { get; set; }
        public decimal Stamp_Duty_Fee_SGD { get; set; }
        public decimal Trans_Levy_Fee_SGD { get; set; }
    
        public virtual Trade Trade { get; set; }
    }
}
