//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRPS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade_Cancelled
    {
        public System.DateTime Business_Date { get; set; }
        public long Trade_No { get; set; }
        public string Trade_Ref { get; set; }
        public string Client_Number { get; set; }
        public string Trade_Type { get; set; }
        public string Sub_Trade_Type { get; set; }
        public string Operation_Type { get; set; }
        public string Market { get; set; }
        public System.DateTime Trade_Date { get; set; }
        public System.DateTime Value_Date { get; set; }
        public string Instrument { get; set; }
        public int Qty { get; set; }
        public int Open_Qty { get; set; }
        public decimal Price { get; set; }
        public string Trade_Curr { get; set; }
        public decimal Trade_Principal { get; set; }
        public string Settle_Curr { get; set; }
        public decimal Settle_Amount { get; set; }
        public decimal Open_Amount { get; set; }
        public decimal Exch_Rate { get; set; }
        public string Mult_Div_Ind { get; set; }
        public decimal Settle_Amount_SGD { get; set; }
        public long Trade_No_Ref1 { get; set; }
        public long Trade_No_Ref2 { get; set; }
        public string Contra_Trade_Ref { get; set; }
        public string Trades_With_Accrued { get; set; }
        public int Accrued_Interest_Days { get; set; }
        public decimal Accrued_Interest_Rate { get; set; }
        public string Accrued_Interest_Curr { get; set; }
        public decimal Accrued_Interest_Amt { get; set; }
        public decimal Last_Done_Price { get; set; }
        public string Entry_Ind { get; set; }
        public string TR_Code { get; set; }
        public string Settle_Code { get; set; }
        public string Settle_Type { get; set; }
        public string Price_Type { get; set; }
        public int Trade_Version { get; set; }
        public string Trade_Status { get; set; }
        public string Settle_Status { get; set; }
        public string Primary_Book { get; set; }
        public string PSMS_Source { get; set; }
        public string SGX_Trade_No { get; set; }
        public string With_Reference { get; set; }
        public string Execution_Number { get; set; }
        public string Trans_Settle_Type { get; set; }
        public string Cash_Payment_Mode { get; set; }
        public string Cash_Payment_Status { get; set; }
        public string Settle_Transform { get; set; }
        public string Trade_Channel { get; set; }
        public System.DateTime Created_Date { get; set; }
        public System.DateTime Amend_Date { get; set; }
        public System.DateTime Version_date { get; set; }
        public int Version_no { get; set; }
        public string EPS_Bank_Name { get; set; }
        public System.DateTime Settle_date { get; set; }
        public string Execution_SalesPerson { get; set; }
        public string FOR_No { get; set; }
        public string Our_Nostro_Account { get; set; }
        public string Our_Nostro_BankName { get; set; }
        public string Parent_Link_Trade { get; set; }
        public string Allocation_Processing_Indicator { get; set; }
    }
}
