//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRPS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade_Status
    {
        public System.DateTime Business_Date { get; set; }
        public long Trade_No { get; set; }
        public string Trade_Ref { get; set; }
        public string Settle_Status { get; set; }
        public Nullable<System.DateTime> Settle_date { get; set; }
        public string Trade_Type { get; set; }
        public Nullable<System.DateTime> Import_date { get; set; }
    }
}
