//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRPS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Type
    {
        public string Trans_Type { get; set; }
        public string Operation_Type { get; set; }
        public string Payment_Mode { get; set; }
        public string Trans_Code { get; set; }
        public string Trans_Desc { get; set; }
    }
}
