//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRPS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warrant
    {
        public string Instr_Ref { get; set; }
        public string Warrant_Type { get; set; }
        public string Settle_Type { get; set; }
        public string Payment_Curr { get; set; }
        public string Call_Put_Ind { get; set; }
        public decimal Strike_Price { get; set; }
        public System.DateTime Expiry_Date { get; set; }
        public System.DateTime Last_Notice_Date { get; set; }
        public string Price_Type { get; set; }
        public decimal Ratio { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> Delivery_Date { get; set; }
        public string Underlying_Instr { get; set; }
        public Nullable<System.DateTime> Separation_Date { get; set; }
        public string Parent_Code { get; set; }
    
        public virtual Instrument Instrument { get; set; }
    }
}
